CREATE TABLE reader(
                       id BIGINT generated by default as identity primary key,
                       phone_number varchar(12) NOT NULL UNIQUE ,
                       name varchar NOT NULL,
                       surname varchar NOT NULL,
                       gender varchar NOT NULL,
                       date_birth DATE NOT NULL
);

CREATE TABLE book(
                     id BIGINT generated by default as identity primary key,
                     name varchar NOT NULL,
                     year_publication INTEGER CHECK (year_publication <= EXTRACT(YEAR FROM CURRENT_DATE)) NOT NULL
);

CREATE TABLE author(
                       id BIGINT generated by default as identity primary key,
                       name varchar NOT NULL,
                       surname varchar NOT NULL,
                       date_birth DATE NOT NULL
);

CREATE table books_authors(
                              author_id int references author(id),
                              book_id int references book(id),
                              PRIMARY KEY (author_id, book_id)
);

CREATE TABLE transaction(
                            id BIGINT generated by default as identity primary key,
                            type_operation varchar NOT NULL,
                            date_time_operation TIMESTAMP NOT NULL,
                            reader_id int NOT NULL,
                            book_id int NOT NULL,
                            FOREIGN KEY (reader_id) REFERENCES reader(id) ON DELETE CASCADE ON UPDATE CASCADE,
                            FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE employee(
                         id BIGINT generated by default as identity primary key,
                         login varchar NOT NULL UNIQUE,
                         password varchar NOT NULL
);

INSERT INTO author (name, surname, date_birth) VALUES
                                                   ('Лев', 'Толстой', '1828-09-09'),
                                                   ('Фёдор', 'Достоевский', '1821-11-11'),
                                                   ('Антон', 'Чехов', '1860-01-29'),
                                                   ('Александр', 'Пушкин', '1799-06-06'),
                                                   ('Николай', 'Гоголь', '1809-03-31');


INSERT INTO book (name, year_publication) VALUES
                                              ('Война и мир', 1869),
                                              ('Преступление и наказание', 1866),
                                              ('Чайка', 1896),
                                              ('Евгений Онегин', 1833),
                                              ('Мертвые души', 1842),
                                              ('Анна Каренина', 1877),
                                              ('Идиот', 1869),
                                              ('Три сестры', 1901),
                                              ('Руслан и Людмила', 1820),
                                              ('Нос', 1836);


INSERT INTO books_authors (author_id, book_id) VALUES
                                                   (1, 1),
                                                   (1, 6),
                                                   (2, 2),
                                                   (2, 7),
                                                   (3, 3),
                                                   (3, 8),
                                                   (4, 4),
                                                   (4, 9),
                                                   (5, 5),
                                                   (5, 10);

INSERT INTO reader (phone_number, name, surname, gender, date_birth) VALUES
                                                                         ('89161234567', 'Иван', 'Иванов', 'MAN', '1985-02-20'),
                                                                         ('89261234567', 'Александр', 'Петров', 'MAN', '1990-05-15'),
                                                                         ('89361234567', 'Мария', 'Смирнова', 'WOMAN', '1982-08-10'),
                                                                         ('89461234567', 'Екатерина', 'Кузнецова', 'WOMAN', '1995-11-01'),
                                                                         ('89561234567', 'Дмитрий', 'Попов', 'MAN', '1988-07-30'),
                                                                         ('89661234567', 'Ольга', 'Михайлова', 'MAN', '1984-04-18'),
                                                                         ('89761234567', 'Николай', 'Васильев', 'MAN', '1993-12-25'),
                                                                         ('89861234567', 'Анастасия', 'Новикова', 'WOMAN', '1991-06-23'),
                                                                         ('89961234567', 'Петр', 'Лебедев', 'MAN', '1987-09-14'),
                                                                         ('89171234567', 'Татьяна', 'Федорова', 'WOMAN', '1992-01-12'),
                                                                         ('89271234567', 'Владимир', 'Соколов', 'MAN', '1980-03-05'),
                                                                         ('89371234567', 'Ирина', 'Тимофеева', 'WOMAN', '1994-10-28');

INSERT INTO transaction (type_operation, date_time_operation, reader_id, book_id) VALUES
                                                                                      ('TAKE', '2024-11-01 10:30:00', 1, 1),
                                                                                      ('TAKE', '2024-11-02 14:45:00', 1, 3),
                                                                                      ('TAKE', '2024-11-03 09:20:00', 1, 2),
                                                                                      ('TAKE', '2024-11-04 16:00:00', 2, 5),
                                                                                      ('TAKE', '2024-11-05 11:10:00', 2, 4),
                                                                                      ('TAKE', '2024-11-06 13:25:00', 2, 6),
                                                                                      ('TAKE', '2024-11-07 17:40:00', 2, 7),
                                                                                      ('TAKE', '2024-11-08 10:55:00', 3, 8),
                                                                                      ('TAKE', '2024-11-09 12:05:00', 9, 9),
                                                                                      ('TAKE', '2024-11-10 15:15:00', 5, 10),
                                                                                      ('TAKE', '2024-11-11 11:30:00', 11, 4),
                                                                                      ('TAKE', '2024-11-12 18:20:00', 12, 4),
                                                                                      ('TAKE', '2024-11-13 09:10:00', 1, 2),
                                                                                      ('RETURN', '2024-11-14 14:25:00', 1, 1),
                                                                                      ('RETURN', '2024-11-15 16:40:00', 1, 3),
                                                                                      ('RETURN', '2024-11-16 10:30:00', 2, 5),
                                                                                      ('RETURN', '2024-11-17 12:50:00', 2, 6),
                                                                                      ('RETURN', '2024-11-18 17:10:00', 3, 8),
                                                                                      ('RETURN', '2024-11-19 11:45:00', 5, 10),
                                                                                      ('RETURN', '2024-11-20 15:35:00', 1, 2);

