CREATE TABLE reader(
                       id BIGINT generated by default as identity primary key,
                       phone_number varchar(12) NOT NULL UNIQUE ,
                       name varchar NOT NULL,
                       surname varchar NOT NULL,
                       gender varchar NOT NULL,
                       date_birth DATE NOT NULL
);

CREATE TABLE book(
                     id BIGINT generated by default as identity primary key,
                     name varchar NOT NULL,
                     year_publication INTEGER CHECK (year_publication <= EXTRACT(YEAR FROM CURRENT_DATE)) NOT NULL
);

CREATE TABLE author(
                       id BIGINT generated by default as identity primary key,
                       name varchar NOT NULL,
                       surname varchar NOT NULL,
                       date_birth DATE NOT NULL
);

CREATE table books_authors(
                              author_id int references author(id),
                              book_id int references book(id),
                              PRIMARY KEY (author_id, book_id)
);

CREATE TABLE transaction(
                            id BIGINT generated by default as identity primary key,
                            type_operation varchar NOT NULL,
                            date_time_operation TIMESTAMP NOT NULL,
                            reader_id int NOT NULL,
                            book_id int NOT NULL,
                            FOREIGN KEY (reader_id) REFERENCES reader(id) ON DELETE CASCADE ON UPDATE CASCADE,
                            FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE employee(
                         id BIGINT generated by default as identity primary key,
                         login varchar NOT NULL UNIQUE,
                         password varchar NOT NULL
);